/**
 * Compatibility shim. New code should import from `@llazyemail/component-types`.
 * This folder is the package that will move out of this repository.
 */
export type {
  ButtonComponent,
  ButtonProps,
  HeadingComponent,
  HeadingProps,
  HtmlString,
  ImageComponent,
  ImageLinkedComponent,
  ImageLinkedProps,
  ImageProps,
  ItalicComponent,
  ItalicProps,
  LinkComponent,
  LinkProps,
  ListComponent,
  ListItemComponent,
  ListItemProps,
  ListProps,
  MainTitleImageComponent,
  MainTitleImageProps,
  ParagraphComponent,
  ParagraphProps,
  ParagraphUpdatedComponent,
  ParagraphUpdatedProps,
  SeparatorComponent,
  SeparatorProps,
  StrongComponent,
  StrongProps,
  SubtitleComponent,
  SubtitleProps,
  TitleComponent,
  TitleProps,
  TypographyComponent,
  TypographyComponents,
} from '@llazyemail/component-types';
